
const books = [
  {
    "id": 11,
    "title": "Alice's Adventures in Wonderland",
    "author": "Carroll, Lewis",
    "subjects": "Alice (Fictitious character from Carroll) -- Juvenile fiction, Children's stories, Fantasy fiction, Imaginary places -- Juvenile fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Children & Young Adult Reading, Category: Classics of Literature, Category: Novels, Children's Literature",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 46226,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/11.html.images"
  },
  {
    "id": 12,
    "title": "Through the Looking-Glass",
    "author": "Carroll, Lewis",
    "subjects": "Alice (Fictitious character from Carroll) -- Juvenile fiction, Children's stories, Fantasy fiction, Imaginary places -- Juvenile fiction",
    "translators": null,
    "bookshelves": "Best Books Ever Listings, Category: British Literature, Category: Children & Young Adult Reading, Category: Novels, Children's Literature",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 10740,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/12/pg12.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/12.html.images"
  },
  {
    "id": 16,
    "title": "Peter Pan : $b [Peter and Wendy]",
    "author": "Barrie, J. M. (James Matthew)",
    "subjects": "Fairies -- Fiction, Fantasy literature, Never-Never Land (Imaginary place) -- Fiction, Peter Pan (Fictitious character) -- Fiction, Pirates -- Fiction",
    "translators": null,
    "bookshelves": "Category: Adventure, Category: British Literature, Category: Children & Young Adult Reading, Category: Classics of Literature, Category: Novels, Children's Literature, Movie Books",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 13200,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/16/pg16.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/16.html.images"
  },
  {
    "id": 23,
    "title": "Narrative of the Life of Frederick Douglass, an American Slave",
    "author": "Douglass, Frederick",
    "subjects": "Abolitionists -- United States -- Biography, African American abolitionists -- Biography, Douglass, Frederick, 1818-1895, Enslaved persons -- United States -- Biography",
    "translators": null,
    "bookshelves": "African American Writers, Category: Biographies, Category: History - American, Slavery",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 13400,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/23/pg23.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/23.html.images"
  },
  {
    "id": 43,
    "title": "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "author": "Stevenson, Robert Louis",
    "subjects": "Horror tales, London (England) -- Fiction, Multiple personality -- Fiction, Physicians -- Fiction, Psychological fiction, Science fiction, Self-experimentation in medicine -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Crime, Thrillers and Mystery, Category: Novels, Horror, Movie Books, Precursors of Science Fiction",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 29426,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/43/pg43.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/43.html.images"
  },
  {
    "id": 46,
    "title": "A Christmas Carol in Prose; Being a Ghost Story of Christmas",
    "author": "Dickens, Charles",
    "subjects": "Christmas stories, Ghost stories, London (England) -- Fiction, Misers -- Fiction, Poor families -- Fiction, Scrooge, Ebenezer (Fictitious character) -- Fiction, Sick children -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Novels, Children's Literature, Christmas",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 11865,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/46/pg46.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/46.html.images"
  },
  {
    "id": 55,
    "title": "The Wonderful Wizard of Oz",
    "author": "Baum, L. Frank (Lyman Frank)",
    "subjects": "Courage -- Juvenile fiction, Cowardly Lion (Fictitious character) -- Juvenile fiction, Cyclones -- Juvenile fiction, Dreams -- Juvenile fiction, Fantasy literature, Gale, Dorothy (Fictitious character) -- Juvenile fiction, Good and evil -- Juvenile fiction, Home -- Juvenile fiction, Oz (Imaginary place) -- Juvenile fiction, Scarecrow (Fictitious character from Baum) -- Juvenile fiction, Tin Woodman (Fictitious character) -- Juvenile fiction, Toto (Fictitious character) -- Juvenile fiction, Witches -- Juvenile fiction, Wizard of Oz (Fictitious character) -- Juvenile fiction",
    "translators": null,
    "bookshelves": "Category: Adventure, Category: American Literature, Category: Children & Young Adult Reading, Category: Science-Fiction & Fantasy, Children's Literature, Fantasy",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 11991,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/55/pg55.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/55.html.images"
  },
  {
    "id": 74,
    "title": "The Adventures of Tom Sawyer, Complete",
    "author": "Twain, Mark",
    "subjects": "Adventure stories, Bildungsromans, Boys -- Fiction, Child witnesses -- Fiction, Humorous stories, Male friendship -- Fiction, Mississippi River Valley -- Fiction, Missouri -- Fiction, Runaway children -- Fiction, Sawyer, Tom (Fictitious character) -- Fiction",
    "translators": null,
    "bookshelves": "Banned Books List from the American Library Association, Banned Books from Anne Haight's list, Category: Adventure, Category: American Literature, Category: Classics of Literature, Category: Novels",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 19316,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/74/pg74.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/74.html.images"
  },
  {
    "id": 76,
    "title": "Adventures of Huckleberry Finn",
    "author": "Twain, Mark",
    "subjects": "Adventure stories, Bildungsromans, Boys -- Fiction, Finn, Huckleberry (Fictitious character) -- Fiction, Fugitive slaves -- Fiction, Humorous stories, Male friendship -- Fiction, Mississippi River -- Fiction, Missouri -- Fiction, Race relations -- Fiction, Runaway children -- Fiction",
    "translators": null,
    "bookshelves": "Banned Books List from the American Library Association, Banned Books from Anne Haight's list, Best Books Ever Listings, Category: Adventure, Category: American Literature, Category: Classics of Literature, Category: Novels",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 20384,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/76/pg76.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/76.html.images"
  },
  {
    "id": 84,
    "title": "Frankenstein; Or, The Modern Prometheus",
    "author": "Shelley, Mary Wollstonecraft",
    "subjects": "Frankenstein's monster (Fictitious character) -- Fiction, Frankenstein, Victor (Fictitious character) -- Fiction, Gothic fiction, Horror tales, Monsters -- Fiction, Science fiction, Scientists -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Novels, Category: Science-Fiction & Fantasy, Gothic Fiction, Movie Books, Precursors of Science Fiction, Science Fiction by Women",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 95833,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/84.html.images"
  },
  {
    "id": 98,
    "title": "A Tale of Two Cities",
    "author": "Dickens, Charles",
    "subjects": "British -- France -- Paris -- Fiction, Executions and executioners -- Fiction, France -- History -- Revolution, 1789-1799 -- Fiction, French -- England -- London -- Fiction, Historical fiction, London (England) -- History -- 18th century -- Fiction, Lookalikes -- Fiction, Paris (France) -- History -- 1789-1799 -- Fiction, War stories",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Historical Novels, Historical Fiction",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 25136,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/98/pg98.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/files/98/98-0.txt"
  },
  {
    "id": 100,
    "title": "The Complete Works of William Shakespeare",
    "author": "Shakespeare, William",
    "subjects": "English drama -- Early modern and Elizabethan, 1500-1600",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Plays/Films/Dramas, Category: Poetry, Plays",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 59579,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/100/pg100.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/100.html.images"
  },
  {
    "id": 145,
    "title": "Middlemarch",
    "author": "Eliot, George",
    "subjects": "Bildungsromans, City and town life -- Fiction, Didactic fiction, Domestic fiction, England -- Fiction, Love stories, Married people -- Fiction, Young women -- Fiction",
    "translators": null,
    "bookshelves": "Best Books Ever Listings, Category: British Literature, Category: Classics of Literature, Category: Novels, Historical Fiction",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 54977,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/145/pg145.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/145.html.images"
  },
  {
    "id": 174,
    "title": "The Picture of Dorian Gray",
    "author": "Wilde, Oscar",
    "subjects": "Appearance (Philosophy) -- Fiction, Conduct of life -- Fiction, Didactic fiction, Great Britain -- History -- Victoria, 1837-1901 -- Fiction, London (England) -- History -- 1800-1950 -- Fiction, Paranormal fiction, Portraits -- Fiction, Supernatural -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Novels, Gothic Fiction, Movie Books",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 28774,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/174/pg174.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/174.html.images"
  },
  {
    "id": 205,
    "title": "Walden, and On The Duty Of Civil Disobedience",
    "author": "Thoreau, Henry David",
    "subjects": "Authors, American -- 19th century -- Biography, Civil disobedience, Government, Resistance to, Natural history -- Massachusetts -- Walden Woods, Solitude, Thoreau, Henry David, 1817-1862 -- Homes and haunts -- Massachusetts -- Walden Woods, Walden Woods (Mass.) -- Social life and customs, Wilderness areas -- Massachusetts -- Walden Woods",
    "translators": null,
    "bookshelves": "Category: American Literature, Category: Essays, Letters & Speeches, Category: Philosophy & Ethics",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 15989,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/205/pg205.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/205.html.images"
  },
  {
    "id": 219,
    "title": "Heart of Darkness",
    "author": "Conrad, Joseph",
    "subjects": "Africa -- Fiction, Degeneration -- Fiction, Europeans -- Africa -- Fiction, Imperialism -- Fiction, Psychological fiction, Trading posts -- Fiction",
    "translators": null,
    "bookshelves": "Best Books Ever Listings, Category: British Literature, Category: Classics of Literature, Category: Novels, Movie Books",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 10815,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/219/pg219.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/219.html.images"
  },
  {
    "id": 345,
    "title": "Dracula",
    "author": "Stoker, Bram",
    "subjects": "Dracula, Count (Fictitious character) -- Fiction, Epistolary fiction, Gothic fiction, Horror tales, Transylvania (Romania) -- Fiction, Vampires -- Fiction, Whitby (England) -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Crime, Thrillers and Mystery, Category: Novels, Category: Science-Fiction & Fantasy, Gothic Fiction, Horror, Movie Books, Mystery Fiction",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 38150,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/345/pg345.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/345.html.images"
  },
  {
    "id": 394,
    "title": "Cranford",
    "author": "Gaskell, Elizabeth Cleghorn",
    "subjects": "England -- Fiction, Female friendship -- Fiction, Older women -- Fiction, Pastoral fiction, Sisters -- Fiction, Villages -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Novels",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 44579,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/394/pg394.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/394.html.images"
  },
  {
    "id": 408,
    "title": "The Souls of Black Folk",
    "author": "Du Bois, W. E. B. (William Edward Burghardt)",
    "subjects": "African Americans",
    "translators": null,
    "bookshelves": "African American Writers, Category: Essays, Letters & Speeches, Category: History - American, Category: Politics, Category: Sociology",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 15429,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/408/pg408.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/files/408/408-0.txt"
  },
  {
    "id": 514,
    "title": "Little Women",
    "author": "Alcott, Louisa May",
    "subjects": "Autobiographical fiction, Bildungsromans, Domestic fiction, Family life -- New England -- Fiction, March family (Fictitious characters) -- Fiction, Mothers and daughters -- Fiction, New England -- Fiction, Sisters -- Fiction, Young women -- Fiction",
    "translators": null,
    "bookshelves": "Category: American Literature, Category: Classics of Literature, Category: Novels, Children's Literature",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 11175,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/514/pg514.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/514.html.images"
  },
  {
    "id": 730,
    "title": "Oliver Twist",
    "author": "Dickens, Charles",
    "subjects": "Bildungsromans, Boys -- Fiction, Criminals -- Fiction, Kidnapping victims -- Fiction, London (England) -- Fiction, Orphans -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Novels",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 11123,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/730/pg730.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/730.html.images"
  },
  {
    "id": 768,
    "title": "Wuthering Heights",
    "author": "BrontÃ«, Emily",
    "subjects": "Domestic fiction, Foundlings -- Fiction, Heathcliff (Fictitious character : BrontÃ«) -- Fiction, Love stories, Psychological fiction, Rejection (Psychology) -- Fiction, Revenge -- Fiction, Rural families -- Fiction, Triangles (Interpersonal relations) -- Fiction, Yorkshire (England) -- Fiction",
    "translators": null,
    "bookshelves": "Best Books Ever Listings, Category: British Literature, Category: Classics of Literature, Category: Novels, Gothic Fiction, Movie Books",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 15781,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/768/pg768.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/768.html.images"
  },
  {
    "id": 844,
    "title": "The Importance of Being Earnest: A Trivial Comedy for Serious People",
    "author": "Wilde, Oscar",
    "subjects": "Comedy plays, England -- Drama, Foundlings -- Drama, Identity (Psychology) -- Drama",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Plays/Films/Dramas, Plays",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 19393,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/844/pg844.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/files/844/844-0.txt"
  },
  {
    "id": 1023,
    "title": "Bleak House",
    "author": "Dickens, Charles",
    "subjects": "Bildungsromans, Domestic fiction, Guardian and ward -- Fiction, Illegitimate children -- Fiction, Inheritance and succession -- Fiction, Legal stories, London (England) -- Fiction, Young women -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Novels",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 10806,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1023/pg1023.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1023.html.images"
  },
  {
    "id": 1080,
    "title": "A Modest Proposal: For preventing the children of poor people in Ireland, from being a burden on their parents or country, and for making them beneficial to the publick",
    "author": "Swift, Jonathan",
    "subjects": "Ireland -- Politics and government -- 18th century -- Humor, Political satire, English, Religious satire, English",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Essays, Letters & Speeches",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 19972,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1080/pg1080.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/files/1080/1080-0.txt"
  },
  {
    "id": 1184,
    "title": "The Count of Monte Cristo",
    "author": "Dumas, Alexandre, Maquet, Auguste",
    "subjects": "Adventure stories, DantÃ¨s, Edmond (Fictitious character) -- Fiction, France -- History -- 19th century -- Fiction, Historical fiction, Pirates -- Fiction, Prisoners -- Fiction, Revenge -- Fiction",
    "translators": null,
    "bookshelves": "Adventure, Category: Adventure, Category: Classics of Literature, Category: French Literature, Category: Novels, Movie Books",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 22069,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1184/pg1184.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1184.html.images"
  },
  {
    "id": 1232,
    "title": "The Prince",
    "author": "Machiavelli, NiccolÃ²",
    "subjects": "Political ethics -- Early works to 1800, Political science -- Philosophy -- Early works to 1800, State, The -- Early works to 1800",
    "translators": "Marriott, W. K. (William Kenaz)",
    "bookshelves": "Banned Books from Anne Haight's list, Category: History - Early Modern (c. 1450-1750), Category: Philosophy & Ethics, Category: Politics, Harvard Classics, Philosophy, Politics",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 19770,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1232/pg1232.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1232.html.images"
  },
  {
    "id": 1251,
    "title": "Le Morte d'Arthur: Volume 1",
    "author": "Malory, Thomas, Sir",
    "subjects": "Arthur, King -- Legends, Arthurian romances",
    "translators": null,
    "bookshelves": "Arthurian Legends, Category: British Literature, Category: Classics of Literature, Category: Historical Novels, Category: Mythology, Legends & Folklore, Fantasy",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 10646,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1251/pg1251.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/files/1251/1251-0.txt"
  },
  {
    "id": 1260,
    "title": "Jane Eyre: An Autobiography",
    "author": "BrontÃ«, Charlotte",
    "subjects": "Bildungsromans, Charity-schools -- Fiction, Country homes -- Fiction, England -- Fiction, Fathers and daughters -- Fiction, Governesses -- Fiction, Love stories, Married people -- Fiction, Mentally ill women -- Fiction, Orphans -- Fiction, Young women -- Fiction",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Novels, Category: Romance",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 23543,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1260/pg1260.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1260.html.images"
  },
  {
    "id": 1342,
    "title": "Pride and Prejudice",
    "author": "Austen, Jane",
    "subjects": "Courtship -- Fiction, Domestic fiction, England -- Fiction, Love stories, Sisters -- Fiction, Social classes -- Fiction, Young women -- Fiction",
    "translators": null,
    "bookshelves": "Best Books Ever Listings, Category: British Literature, Category: Classics of Literature, Category: Novels, Category: Romance, Harvard Classics",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 59702,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1342.html.images"
  },
  {
    "id": 1399,
    "title": "Anna Karenina",
    "author": "Tolstoy, Leo, graf",
    "subjects": "Adultery -- Fiction, Didactic fiction, Love stories, Married women -- Fiction, Russia -- Fiction",
    "translators": "Garnett, Constance",
    "bookshelves": "Best Books Ever Listings, Category: Classics of Literature, Category: Novels, Category: Russian Literature, Harvard Classics, Movie Books",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 12783,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1399/pg1399.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1399.html.images"
  },
  {
    "id": 1400,
    "title": "Great Expectations",
    "author": "Dickens, Charles",
    "subjects": "Benefactors -- Fiction, Bildungsromans, England -- Fiction, Ex-convicts -- Fiction, Man-woman relationships -- Fiction, Orphans -- Fiction, Revenge -- Fiction, Young men -- Fiction",
    "translators": null,
    "bookshelves": "Best Books Ever Listings, Category: British Literature, Category: Classics of Literature, Category: Novels",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 17070,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1400/pg1400.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1400.html.images"
  },
  {
    "id": 1513,
    "title": "Romeo and Juliet",
    "author": "Shakespeare, William",
    "subjects": "Conflict of generations -- Drama, Juliet (Fictitious character) -- Drama, Romeo (Fictitious character) -- Drama, Tragedies (Drama), Vendetta -- Drama, Verona (Italy) -- Drama, Youth -- Drama",
    "translators": null,
    "bookshelves": "Category: British Literature, Category: Classics of Literature, Category: Plays/Films/Dramas, Category: Romance",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 79945,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1513/pg1513.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1513.html.images"
  },
  {
    "id": 1727,
    "title": "The Odyssey: Rendered into English prose for the use of those who cannot read the original",
    "author": "Homer",
    "subjects": "Epic poetry, Greek -- Translations into English, Homer -- Translations into English, Odysseus, King of Ithaca (Mythological character)",
    "translators": "Butler, Samuel",
    "bookshelves": "Category: Classics of Literature, Category: Mythology, Legends & Folklore, Category: Poetry, Classical Antiquity, Harvard Classics",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 14814,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1727/pg1727.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1727.html.images"
  },
  {
    "id": 1952,
    "title": "The Yellow Wallpaper",
    "author": "Gilman, Charlotte Perkins",
    "subjects": "Feminist fiction, Married women -- Psychology -- Fiction, Mentally ill women -- Fiction, Psychological fiction, Sex role -- Fiction",
    "translators": null,
    "bookshelves": "Category: American Literature, Category: Short Stories, Gothic Fiction",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 15959,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1952/pg1952.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1952.html.images"
  },
  {
    "id": 1998,
    "title": "Thus Spake Zarathustra: A Book for All and None",
    "author": "Nietzsche, Friedrich Wilhelm",
    "subjects": "Philosophy, German, Superman (Philosophical concept)",
    "translators": "Common, Thomas",
    "bookshelves": "Category: Classics of Literature, Category: German Literature, Category: Philosophy & Ethics, Philosophy",
    "languages": "en",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 23279,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/1998/pg1998.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/ebooks/1998.html.images"
  },
  {
    "id": 2000,
    "title": "Don Quijote",
    "author": "Cervantes Saavedra, Miguel de",
    "subjects": "Knights and knighthood -- Spain -- Fiction, Picaresque literature, Romances, Spain -- Social life and customs -- 16th century -- Fiction",
    "translators": null,
    "bookshelves": "6 Best Loved Spanish Literary Classics, Best Books Ever Listings, Category: Classics of Literature, Category: Novels, Harvard Classics",
    "languages": "es",
    "copyright": "FALSE",
    "media_type": "Text",
    "download_count": 15332,
    "description": "N/A",
    "cover_image_url": "https://www.gutenberg.org/cache/epub/2000/pg2000.cover.medium.jpg",
    "book_url": "https://www.gutenberg.org/files/2000/2000-0.txt"
  }
]
export default books;
